# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
warnings_are_errors: false
latex: false
r_check_args: --as-cran

matrix:
  include:
    - os: linux
      r: release
      r_packages:
        - covr
        - pkgdown
      after_success:
        - travis_wait 20 Rscript -e 'covr::codecov(quiet=FALSE)'
        - R CMD INSTALL .
        - Rscript -e 'pkgdown::build_site()'
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_PAT
          keep-history: true
          local-dir: docs
          on:
            branch: master
    - os: linux
      r: devel
    - os: osx
      r: release

before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'
  - export _R_CHECK_TIMINGS_=0  ## Report on timing for all tests

notifications:
  email:
    on_success: change
    on_failure: change
