# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

E_step_covariates <- function(Y, cov, gamma, beta, Tau, alpha) {
    .Call('_missSBM_E_step_covariates', PACKAGE = 'missSBM', Y, cov, gamma, beta, Tau, alpha)
}

optimize_Mstep_covariates_undirected <- function(param, Y, cov, Tau) {
    .Call('_missSBM_optimize_Mstep_covariates_undirected', PACKAGE = 'missSBM', param, Y, cov, Tau)
}

optimize_Mstep_covariates_directed <- function(param, Y, cov, Tau) {
    .Call('_missSBM_optimize_Mstep_covariates_directed', PACKAGE = 'missSBM', param, Y, cov, Tau)
}

#' @export
roundProduct <- function(X, beta) {
    .Call('_missSBM_roundProduct', PACKAGE = 'missSBM', X, beta)
}

vExpec_covariates <- function(Y, gamma, beta, cov, Tau, alpha) {
    .Call('_missSBM_vExpec_covariates', PACKAGE = 'missSBM', Y, gamma, beta, cov, Tau, alpha)
}

